name: Security and Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dependency-scan:
    name: Scan Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dependency Review
        uses: actions/dependency-review-action@v2

      - name: Install dependencies
        run: npm install # Замените на ваш пакетный менеджер

      - name: Run tests
        run: npm test

  codeql-scan:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript' # Добавьте языки, используемые в проекте

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
